### ISSUE TITLE
Remote stream recieved but can't be displayed.

### ISSUE THREAD

**Issue by photizzo** [sergiopaniego/WebRTCAndroidExample#3]
Great work you've done here. I set up everything successfully and ran the code but it doesn't work. The app just shows the face of the front camera it captures but the remote view that should display the remote peer is black. Can you give a simple work through how it works for you or better still a sample demo video.

**Comment by mrgames13** [comment]
I have the same problem. The stream pops out at the remote peerconnection, but the view stays empty. Could you please tell us, what we're doing wrong?

**Comment by sergiopaniego** [comment]
The problem would be related to the fact that the server doesn't store localPeer's iceCandidates and as soon as they arrive, they are sent to the peers listening. So if the remotePeer isn't created immediately after the start button is pressed, those iceCandidates are lost and the remotePeer doesn't display anything because the connection isn't stablished. The quick and bad workaround of the issue would be just pressing start button and then quickly the call button just as it's available. 
It would be a great idea to store iceCandidates and possibly more info related to it on the server so it gets sent when needed. This is just a concept project so it's not supposed to be completely accurate. Hope this helps 😄
